server {
    listen 80;
    server_name id.worldofunreal.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name id.worldofunreal.com;

    ssl_certificate     /usr/local/etc/letsencrypt/live/mail.worldofunreal.com/fullchain.pem;
    ssl_certificate_key /usr/local/etc/letsencrypt/live/mail.worldofunreal.com/privkey.pem;
    include snippets/ssl-params.conf;

    location / {
        proxy_pass http://127.0.0.1:25570;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
    }
}
